-- Uploaded files that survive a restart.
--
-- The store was an in-process `Map`, which meant every resume and every
-- deliverable died with the server. That is fine for a demonstration and
-- indefensible the moment a learner attaches a real transcript: the record
-- would say a file was accepted, and the file would be gone.
--
-- **The bytes live in Postgres, not in object storage, and that is a choice
-- with a ceiling.** What it buys is worth naming: one backup covers the
-- records and the documents together, there is no second set of credentials
-- to hold or rotate, a file cannot be orphaned by a failed write on the other
-- side, and the access rules that already scope every read are the same rules
-- protecting the bytes. What it costs is that a read loads the whole file into
-- memory and the database carries the bulk. At the pilot's size — resumes and
-- deliverables, capped at 5MB and 20MB, for a few hundred learners — that is a
-- trade worth making. Past a few thousand files, or once video appears, the
-- `FileStore` interface is the seam an S3 or Blob adapter plugs into, and this
-- table becomes the metadata for it.

BEGIN;

CREATE TABLE uploaded_files (
  -- Generated by the application, never derived from the filename. That is
  -- what actually defeats traversal: a key the client cannot influence cannot
  -- point anywhere. Not a content hash either, which would let someone confirm
  -- they hold the same file as a learner, and not a sequence, which would let
  -- them walk the store.
  key           text PRIMARY KEY,
  purpose       text NOT NULL,
  -- Metadata only. Never used as a path, and never trusted — it is the one
  -- field here the uploader chose.
  filename      text NOT NULL,
  -- Assigned from the validated extension, never echoed from the client. An
  -- attacker who could pick the response's content type could pick how a
  -- browser executes it.
  content_type  text NOT NULL,
  bytes         integer NOT NULL,
  uploaded_by   text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  uploaded_at   timestamptz NOT NULL DEFAULT now(),
  -- Every file here concerns exactly one learner, and retrieval authorization
  -- follows that attachment rather than the uploader — a college uploading on
  -- a learner's behalf must not widen who can read it.
  student_id    text NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  application_id text REFERENCES applications(id) ON DELETE CASCADE,
  -- Quarantined on arrival. Only `clean` is retrievable, and the check runs on
  -- read rather than on write, so a file that never gets scanned stays dark.
  scan          text NOT NULL DEFAULT 'pending',
  content       bytea NOT NULL,

  CONSTRAINT scan_status_known CHECK (scan IN ('pending', 'clean', 'infected')),
  CONSTRAINT bytes_non_negative CHECK (bytes >= 0)
);

-- The purge sweeps by learner, so that is the index that has to exist. The
-- retention schedule anonymises a learner's record rather than deleting it,
-- which means nothing cascades from here — the files have to be removed on
-- purpose, and `purgeLearnerIdentity` is what does it.
CREATE INDEX uploaded_files_student_idx ON uploaded_files (student_id);

-- Quarantined files are the ones a re-scan has to find, and there should never
-- be many. A partial index keeps that lookup cheap without paying for the rows
-- that are already clean.
CREATE INDEX uploaded_files_pending_idx ON uploaded_files (uploaded_at)
  WHERE scan = 'pending';

COMMIT;
